---
title: "Introduction to Report Writing"
format: 
  html:
    fig-width: 12
    fig-height: 6
    code-fold: show
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    toc: true
    code-copy: true
    number_sections: true
    echo: fenced
engine: knitr
editor: visual
---

::: {.callout-quote title="Henri Poincaré"}
*"We have the duty of formulating, of summarizing, and of communicating our conclusions, in intelligible form, in recognition of the right of other free minds to utilize them in making their own decisions."*
:::

In this section, we will be going though report writing techniques and conventions that will help in you ST117 final project, and the entirety of ST231. Specifically, the pages cover the following:

-   Structuring your Report

    -   <div>

        Reporting descriptive statistics

        </div>

    -   <div>

        Reporting numbers: how many decimal places?

        </div>

    -   <div>

        Presenting your data: tables and graphs

        </div>

-   Styling your Report

    -   <div>

        Use of English

        </div>

-   Proper use of Large Language, and other generative AI models

<div>

Presenting the results of a statistical test 1 Summary 2 2 Introduction 2 3 Structure 2 3.1 Title . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3 3.2 Summary/Abstract . . . . . . . . . . . . . . . . . . . . . . . . . . 3 3.3 Introduction . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3 3.4 Methods . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3 3.5 Results, conclusions and recommendations . . . . . . . . . . . . . 4 3.6 General discussion . . . . . . . . . . . . . . . . . . . . . . . . . . 4 3.7 References . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5 3.8 Appendix . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5 4 Content 5 5 Presentation 5 5.1 Figures, Plots, diagrams, etc. . . . . . . . . . . . . . . . . . . . . 5 5.2 Tables . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6 5.3 Computer output . . . . . . . . . . . . . . . . . . . . . . . . . . . 6 6 Use of English 6 7 Style 7 8 Detailed Preparation 8 9 Afterwards 8

</div>